fix script, avoid stuck when cannot use wget

diff --git a/sw/usefull-stuff/minerstat b/sw/usefull-stuff/minerstat
--- a/sw/usefull-stuff/minerstat
+++ b/sw/usefull-stuff/minerstat
@@ -50,59 +50,53 @@ fi
 IP=$1
 HEADER=$2
 
-ping -c 1 -W 1 $IP > /dev/null 2>&1
-if [ $? -eq 0 ] ; then
+# lets check that miner can be accessed by http
+MINER_MON=$(wget http://admin:admin@${IP}/monitor.php  --timeout=5  --tries=1 -O- 2>/dev/null)
+if [ $? -eq 0 ]
+then
+    echo ${MINER_MON} | jq . >/dev/null 2>&1
+    if [ ! $? -eq 0 ]
+    then
+        wget --post-data "agree=true" "http://admin:admin@${IP}/settings.php" >/dev/null 2>&1
+        MINER_MON=`wget http://admin:admin@${IP}/monitor.php -O- 2>/dev/null`
+        echo ${MINER_MON} | jq . >/dev/null 2>&1
+        if [ ! $? -eq 0 ]
+        then
+            echo $IP,WGET-FAIL
+            exit 1	
+        fi
+    fi
+    MINER_SN=`echo ${MINER_MON} | jq .miner.board_ver`
+    MINER_MAC=`echo ${MINER_MON} | jq .miner.mac`		
+    MINER_FWVER=`echo ${MINER_MON} | jq .miner.fw_ver`
+    MINER_GATE_STATUS=`echo ${MINER_MON} | jq .mg_status`
 
-	MINER_MON=`wget http://admin:admin@${IP}/monitor.php -O- 2>/dev/null`
+    MINER_GH=`echo ${MINER_MON} | jq .stats.ASICstotalrate`
+    CGMINER_5S_GH=`echo ${MINER_MON} | jq .summary[0].MHS5s`
+    ERRORS=`echo ${MINER_MON} | jq .summary[0].HardwareErrors`
+    ACCEPTED=`echo ${MINER_MON} | jq .summary[0].Accepted`
 
-	if [ $? -eq 0 ] ; then
-		echo ${MINER_MON} | jq . >/dev/null 2>&1
-		if [ ! $? -eq 0 ] ; then
-			wget --post-data "agree=true" "http://admin:admin@${IP}/settings.php" >/dev/null 2>&1
-			MINER_MON=`wget http://admin:admin@${IP}/monitor.php -O- 2>/dev/null`
-			echo ${MINER_MON} | jq . >/dev/null 2>&1
-			if [ ! $? -eq 0 ] ; then
-				echo $IP,WGET-FAIL
-				exit 1	
-			fi
-		fi
-		MINER_SN=`echo ${MINER_MON} | jq .miner.board_ver`
-		MINER_MAC=`echo ${MINER_MON} | jq .miner.mac`		
-		MINER_FWVER=`echo ${MINER_MON} | jq .miner.fw_ver`
-		MINER_GATE_STATUS=`echo ${MINER_MON} | jq .mg_status`
+    FRONT_TEMP=`echo ${MINER_MON} | jq .stats.Temparaturefront`
+    REAR_TEMP_TOP=`echo ${MINER_MON} | jq .stats.Temparaturereartop`
+    REAR_TEMP_BOT=`echo ${MINER_MON} | jq .stats.Temparaturerearbot`
 
-		MINER_GH=`echo ${MINER_MON} | jq .stats.ASICstotalrate`
-		CGMINER_5S_GH=`echo ${MINER_MON} | jq .summary[0].MHS5s`
-		ERRORS=`echo ${MINER_MON} | jq .summary[0].HardwareErrors`
-		ACCEPTED=`echo ${MINER_MON} | jq .summary[0].Accepted`
+    POOL1_URL=`echo ${MINER_MON} | jq .conf.pools[0].url`
+    POOL1_WALLET=`echo ${MINER_MON} | jq .conf.pools[0].user`
+    POOL2_URL=`echo ${MINER_MON} | jq .conf.pools[1].url`
+    POOL2_WALLET=`echo ${MINER_MON} | jq .conf.pools[1].user`
+    POOL3_URL=`echo ${MINER_MON} | jq .conf.pools[2].url`
+    POOL3_WALLET=`echo ${MINER_MON} | jq .conf.pools[2].user`
 
-		FRONT_TEMP=`echo ${MINER_MON} | jq .stats.Temparaturefront`
-		REAR_TEMP_TOP=`echo ${MINER_MON} | jq .stats.Temparaturereartop`
-		REAR_TEMP_BOT=`echo ${MINER_MON} | jq .stats.Temparaturerearbot`
+    UNIT_UPTIME=`echo ${MINER_MON} | jq .miner.uptime`
+    CGMINER_UPTIME=`echo ${MINER_MON} | jq .stats.Elapsed`
 
+    if [ "$HEADER" == "1" ]
+    then
+        echo "IP,MINER_SN,MINER_MAC,MINER_FWVER,MINER_GATE_STATUS,MINER_GH,CGMINER_5S_GH,ERRORS,ACCEPTED,FRONT_TEMP,REAR_TEMP_TOP,REAR_TEMP_BOT,POOL1_URL,POOL1_WALLET,POOL2_URL,POOL2_WALLET,POOL3_URL,POOL3_WALLET,UNIT_UPTIME,CGMINER_UPTIME"
+    fi
 
-		POOL1_URL=`echo ${MINER_MON} | jq .conf.pools[0].url`
-		POOL1_WALLET=`echo ${MINER_MON} | jq .conf.pools[0].user`
-		POOL2_URL=`echo ${MINER_MON} | jq .conf.pools[1].url`
-		POOL2_WALLET=`echo ${MINER_MON} | jq .conf.pools[1].user`
-		POOL3_URL=`echo ${MINER_MON} | jq .conf.pools[2].url`
-		POOL3_WALLET=`echo ${MINER_MON} | jq .conf.pools[2].user`
-
-		UNIT_UPTIME=`echo ${MINER_MON} | jq .miner.uptime`
-		CGMINER_UPTIME=`echo ${MINER_MON} | jq .stats.Elapsed`
-		
-		
-
-
-		if [ "$HEADER" == "1" ] ; then
-			echo "IP,MINER_SN,MINER_MAC,MINER_FWVER,MINER_GATE_STATUS,MINER_GH,CGMINER_5S_GH,ERRORS,ACCEPTED,FRONT_TEMP,REAR_TEMP_TOP,REAR_TEMP_BOT,POOL1_URL,POOL1_WALLET,POOL2_URL,POOL2_WALLET,POOL3_URL,POOL3_WALLET,UNIT_UPTIME,CGMINER_UPTIME"
-		fi
-
-		echo "$IP,$MINER_SN,$MINER_MAC,$MINER_FWVER,$MINER_GATE_STATUS,$MINER_GH,$CGMINER_5S_GH,$ERRORS,$ACCEPTED,$FRONT_TEMP,$REAR_TEMP_TOP,$REAR_TEMP_BOT,$POOL1_URL,$POOL1_WALLET,$POOL2_URL,$POOL2_WALLET,$POOL3_URL,$POOL3_WALLET,$UNIT_UPTIME,$CGMINER_UPTIME"
-	else
-		echo $IP,WGET-FAIL
-	fi
+    echo "$IP,$MINER_SN,$MINER_MAC,$MINER_FWVER,$MINER_GATE_STATUS,$MINER_GH,$CGMINER_5S_GH,$ERRORS,$ACCEPTED,$FRONT_TEMP,$REAR_TEMP_TOP,$REAR_TEMP_BOT,$POOL1_URL,$POOL1_WALLET,$POOL2_URL,$POOL2_WALLET,$POOL3_URL,$POOL3_WALLET,$UNIT_UPTIME,$CGMINER_UPTIME"
 
 else
-	echo $IP,NO-PING
+    echo $IP,WGET-FAIL
 fi
