get specific ips, usres, passwords, ssh scp commands etc. outside to constants file

diff --git a/sw/usefull-stuff/pingver_slow b/sw/usefull-stuff/pingver_slow
--- a/sw/usefull-stuff/pingver_slow
+++ b/sw/usefull-stuff/pingver_slow
@@ -1,16 +1,23 @@
 #!/bin/bash
+. $(dirname $0)/constants
+
 
 IP=$1
-ping -c 1 -W 2 $IP > /dev/null 2>&1
-if [ $? -eq 0 ] ; then
 
-	FW=`sshpass -p root ssh -o StrictHostKeyChecking=no root@${IP} cat /fw_ver 2>/dev/null`
-	if [ $? -eq 0 ] ; then 
-		echo $IP,$FW
-	else
-		echo $IP,SSH-FAIL
-	fi
+. $(dirname $0)/pingver ${IP} 3
 
-else
-	echo $IP,NO-PING
-fi
+
+#ping -c 1 -W 2 $IP > /dev/null 2>&1
+#if [ $? -eq 0 ] ; then
+#
+#	FW=`${SSHPASS_CMD} ${DEFAULT_USER}@${IP} cat /fw_ver 2>/dev/null`
+#	if [ $? -eq 0 ] ; then 
+#		echo $IP,$FW
+#	else
+#
+#		echo $IP,SSH-FAIL
+#	fi
+#
+#else
+#	echo $IP,NO-PING
+#fi
