updates

diff --git a/sw/usefull-stuff/updateMinerImage b/sw/usefull-stuff/updateMinerImage
--- a/sw/usefull-stuff/updateMinerImage
+++ b/sw/usefull-stuff/updateMinerImage
@@ -15,15 +15,16 @@ if [ ! -e $IMAGE ] ;
 fi
 echo file $IMAGE exist
 
-
-#strings $IMAGE | grep Linux-3.8.13  > /dev/null 2>&1
-
-#if [ ! $? -eq 0 ] ; 
-#	then echo "\n $IMAGE doesnt seem a valid image file. Aborting!"
-#	exit 3
-#fi
-#echo $IMAGE seem a valid image file. 
-
+mkimage -l $IMAGE | grep SP10_FW  > /dev/null 2>&1
+if [ ! $? -eq 0 ] ; 
+	then mkimage -l $IMAGE | grep Linux-3.8.13  > /dev/null 2>&1
+	if [ ! $? -eq 0 ] ; 
+		then echo "\n $IMAGE doesnt seem a valid image file. Aborting!"
+		exit 3
+	fi
+fi
+ 
+echo $IMAGE seem a valid image file. 
 
 ping -c 1 $MINER > /dev/null 2>&1
 
